config/routes.rb
Zoo::Application.routes.draw do
  resources :settings

  devise_for :users
    
  resources :users

  resources :quizzes

  resources :animals

  get "users/:id/assign_admin_role/" => 'users#assign_admin_role', as: :assign_admin_role
  get "users/:id/remove_admin_role/" => 'users#remove_admin_role', as: :remove_admin_role

  get ":controller/:action"
  
  scope "/pages" do
    get "quizzes/prepare_game" => 'quizzes#prepare_game', :defaults => { :format => 'json' }
  end

  
  root :to => 'pages#home'
  
 # unless Rails.application.config.consider_all_requests_local
  match '*not_found(.*)', to: 'errors#error_404', via: [:get, :post]
 # end


end

app/models/user.rb
class User < ActiveRecord::Base
  after_create :assign_default_role

  validates :username, :presence => :true
  
  rolify
  
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable

  # the user's top score in this difficulty level is updated only if current score is higher
  def update_max_score(difficulty,score)
    update_attributes( :"max_#{difficulty}" =>  [send("max_#{difficulty}"), score.to_i].max  )
  end
  
  # find the 5 highest scoring players at the given level of difficulty
  def self.find_best(diff)
    User.where(diff).order(diff).reverse.first(5)
  end


  private
  
  def assign_default_role
    add_role(:user)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  before_action :set_user, only: [:show, :edit, :update, :destroy, :assign_admin_role, :remove_admin_role]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
	format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # a user can be promoted to admin...
  def assign_admin_role
    @user.add_role :admin
    redirect_to users_path
  end
  
  # ...and demoted back to standard user
  def remove_admin_role
    @user.remove_role :admin
    redirect_to users_path
  end


  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    # if password or username are left blank, they won't be changed
    params[:user][:password] = @user.password if params[:user][:password].blank?
    params[:user][:password_confirmation] = @user.password if params[:user][:password_confirmation].blank?
    params[:user][:username] = @user.username if params[:user][:username].blank?

    respond_to do |format|
      if @user.update(user_params)
	format.html { redirect_to users_path }
	format.json { head :no_content }
      else
	format.html { render action: 'edit' }
	format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
  
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  
    <div class="container_sign">
	
	  <div class="div_field_sign"><br />
	    <%= f.email_field :email, :autofocus => true, placeholder: 'Email'%>
	  </div>
	  
	  <div class="div_field_sign"><br />
	    <%= f.text_field :username, placeholder: 'username' %>
	  </div>

	  <div class="div_field_sign"><br />
	    <%= f.password_field :password, :autocomplete => "off", placeholder: 'New Password (if changing)' %>
	  </div>
	  
	  <div class="div_field_sign"><br />
	    <%= f.password_field :password_confirmation,  placeholder: 'New Password confirmation' %>
	  </div>

    </div>

  
    <div class="div_submit">
    
	<%= f.submit "Update" %>
	
    </div>
  
<% end %>

      
      

app/views/users/edit.html.erb
 <div class="div_sign">
 
    <h2 class="transparent_sign">Editing user</h2>

    <%= render 'form' %>

    <%= link_to 'Show', @user %> |
    <%= link_to 'Back', users_path %>

</div>

app/views/users/index.html.erb
<table class="transparent" align="center" cellspacing="0">

    <thead>
    
	<tr class="legend">	 
	    <th>Username</th>
	    <th>Email</th>
	    <th width="150px">Max-easy  </th>
	    <th width="150px">Max-medium  </th>
	    <th width="150px">Max-hard  </th>
	    <th width="50px"></th>
	    <th width="80px"></th>
	    <th></th>
	    <th></th>
	    <th></th>
	</tr>
	
    </thead>

    <tbody>
    
      <% @users.each do |user| %>
	  <tr><td></td></tr>
	  <tr height="50px">
	      <td class="diff" align="center" width="200px"><%= user.username %></td>
	      <td class="diff" align="center"><%= user.email %></td>
	      <td class="diff" align="center"><%= user.max_easy %></td>
	      <td class="diff" align="center"><%= user.max_medium %></td>
	      <td class="diff" align="center"><%= user.max_hard %></td>

	      <td class="s-e-d"><%= link_to 'Edit', edit_user_path(user) %></td>
	      <td class="s-e-d"><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	      
	      <% if not(user.has_role? :admin) %>
		  <td class="s-e-d"> <%= link_to 'Make_Admin', assign_admin_role_path(user) %> </td>
	      <% elsif user.has_role? :admin %>
	          <% if user != current_user %>
		  <td class="s-e-d"> <%= link_to 'Demote_to_User', remove_admin_role_path(user) %> </td>
		  <% end %>
	      <% end %>
	      
	  </tr>
      <% end %>
      
    </tbody>
    
</table>

<br>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <strong>Username:</strong>
    <%= @user.username %>
</p>

<p>
    <strong>Password:</strong>
    <%= @user.password %>
</p>

<p>
    <strong>Max easy:</strong>
    <%= @user.max_easy %>
</p>

<p>
    <strong>Max medium:</strong>
    <%= @user.max_medium %>
</p>

<p>
    <strong>Max hard:</strong>
    <%= @user.max_hard %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>