config/routes.rb
Zoo::Application.routes.draw do
  resources :settings

  devise_for :users
    
  resources :users

  resources :quizzes

  resources :animals

  get "users/:id/assign_admin_role/" => 'users#assign_admin_role', as: :assign_admin_role
  get "users/:id/remove_admin_role/" => 'users#remove_admin_role', as: :remove_admin_role

  get ":controller/:action"
  
  scope "/pages" do
    get "quizzes/prepare_game" => 'quizzes#prepare_game', :defaults => { :format => 'json' }
  end

  
  root :to => 'pages#home'
  
 # unless Rails.application.config.consider_all_requests_local
  match '*not_found(.*)', to: 'errors#error_404', via: [:get, :post]
 # end


end

app/models/setting.rb
class Setting < ActiveRecord::Base

  validates_presence_of [:optone, :opttwo, :optthree]
  validates_numericality_of [:optone, :opttwo, :optthree], :greater_than => 0, :allow_blank => :true
  validate :enough_quizzes_for_setting
  
  private
  
  # you can't let the user ask for 33 quizzes if you only have 30...
  # (this is a more restrictive validation than necessary, but it should have otherwise evaluted
  # at runtime)
  def enough_quizzes_for_setting
    
    if not(optone.nil?)
      if optone > Quiz.min_amount
	errors[:base] << "There aren't enough quizzes for option one!"
      end
    end
    
    if not(opttwo.nil?)
      if opttwo > Quiz.min_amount
	errors[:base] << "There aren't enough quizzes for option two!"
      end
    end
    
    if not(optthree.nil?)
      if optthree > Quiz.min_amount
	errors[:base] << "There aren't enough quizzes for option three!"
      end
    end
  end
  
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render action: 'show', status: :created, location: @setting }
      else
        format.html { render action: 'new' }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to settings_url }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:optone, :opttwo, :optthree)
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%= form_for(@setting) do |f| %>
  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% @setting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  


  <div class="field">
    <%= f.label "Option one" %><br>
    <%= f.number_field :optone %>
  </div>
  <div class="field">
    <%= f.label "Option two" %><br>
    <%= f.number_field :opttwo %>
  </div>
  <div class="field">
    <%= f.label "Option three" %><br>
    <%= f.number_field :optthree %>
  </div>
  
  <br/>
  <br/>
  <br/>
  

  
  <div class="div_submit">
    <%= f.submit %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<div  class="div_sign" >

<h1 class="transparent_sign">Editing setting</h1>

    <%= render 'form' %>

    <%= link_to 'Back', settings_path %>

</div>

app/views/settings/index.html.erb
<h1>Allow players to choose between these options.</h1>

<table align="center" class="transparent" cellspacing="0">

    <thead>
    
	<tr class="legend">
	    <th width="300px">Option one</th>
	    <th width="300px">Option two</th>
	    <th width="300px">Option three</th>
	    <th></th>
	    <th></th>
	    <th></th>
	</tr>
	
    </thead>

    <tbody>
    
	<% @settings.each do |setting| %>
	
	    <tr>
		<td class="diff" align="center" height="100px"><%= setting.optone %></td>
		<td class="diff" align="center"><%= setting.opttwo %></td>
		<td class="diff" align="center"><%= setting.optthree %></td>
		<td class="diff" align="center"><%= link_to 'Change game options', edit_setting_path(setting) %></td>
	    </tr>
	    
	<% end %>
	
    </tbody>
    
</table>

<br>

app/views/settings/new.html.erb
<h1>New setting</h1>

<%= render 'form' %>

<%= link_to 'Back', settings_path %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <strong>Optone:</strong>
    <%= @setting.optone %>
</p>

<p>
    <strong>Opttwo:</strong>
    <%= @setting.opttwo %>
</p>

<p>
    <strong>Optthree:</strong>
    <%= @setting.optthree %>
</p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>