config/routes.rb
Zoo::Application.routes.draw do
  resources :settings

  devise_for :users
    
  resources :users

  resources :quizzes

  resources :animals

  get "users/:id/assign_admin_role/" => 'users#assign_admin_role', as: :assign_admin_role
  get "users/:id/remove_admin_role/" => 'users#remove_admin_role', as: :remove_admin_role

  get ":controller/:action"
  
  scope "/pages" do
    get "quizzes/prepare_game" => 'quizzes#prepare_game', :defaults => { :format => 'json' }
  end

  
  root :to => 'pages#home'
  
 # unless Rails.application.config.consider_all_requests_local
  match '*not_found(.*)', to: 'errors#error_404', via: [:get, :post]
 # end


end

app/models/animal.rb
class Animal < ActiveRecord::Base
  resourcify

  has_many :quizzes, :dependent => :destroy
  
  has_attached_file :avatar, :styles => { :medium => "640x640>", :thumb => "100x100>" }


 
  has_attached_file :sound 
 
 
  validates :name, :presence => :true, :uniqueness => { :case_sensitive => false }, :format => { :with => %r{\A[A-Z][a-zA-Z\s]*\z}, :allow_blank => true}
 

  validates_attachment_presence :avatar


  validates_attachment_presence :sound
 

  validates_attachment_content_type :sound, 
                :content_type => [ 'application/mp3', 'application/x-mp3', 'application/force-download', 'audio/mpeg', 'audio/mp3' ], 
               :message => 'file must be of filetype .mp3' 

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)


    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render action: 'show', status: :created, location: @animal }
      else
        format.html { render action: 'new' }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end




  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    # we also need to destroy quizzes associated to this animal, if any
    @quiz=Quiz.where(animal_id: @animal.id)
    @quiz2=Quiz.where(alternative_id:  @animal.id)
    @quiz.each do |q|
      q.destroy
    end
    @quiz2.each do |p|
      p.destroy
    end
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:name, :avatar, :sound)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_form.html.erb
<%= form_for(@animal) do |f| %>
  
    <% if @animal.errors.any? %>
    
      <div id="error_explanation">
      
	<h2><%= pluralize(@animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

	  <ul>
	      <% @animal.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	      <% end %>
	  </ul>
	  
      </div>
      
    <% end %>

    <div class="field">
	<p/>
	<%= f.text_field :name, placeholder: 'Animal name'%>
    </div>

    <div class="field">
	<br/>
	<%= f.label :avatar %>
	<br/><br/>
	<%= f.file_field :avatar %>
    </div>
    
    <p/>
    
    <div class="field">
	<br/>
	<%= f.label :sound %>
	<br/><br/>
	<%= f.file_field :sound %>
    </div>
    
    <br/>
    
    <div class="actions">
      <%= f.submit %>
    </div>
    
<% end %>
  
<br/>

app/views/animals/edit.html.erb
<div class="center-div">
    <table class="transparent" >

	<tr><th class="legend">Editing animal</th></tr>
	<tr><td></td></tr>
	<tr>
	    <td>
		<%= render 'form' %>
		<%= link_to 'Show', @animal %> |
		<%= link_to 'Back', animals_path %>
	    </td>
	</tr>

    </table>
</div>

app/views/animals/index.html.erb
<div class="center-div">
    <% if can? :create, Animal %>
    <%= button_to 'New Animal', new_animal_path, method: :get, id: "new-animal-button"  %>
    <% end %>
</div>

<table class="transparent" align="center" cellspacing="0" border="0">

    <thead>
  
	<tr class="legend">
	    <th>Name</th>
	    <th>Avatar</th>
	    <th>Sound</th>
	    <th></th>
	    <th></th>
	    <th></th>
	</tr>
  
    </thead>

    <tbody>
    
	<% @animals.each do |animal| %>
	      <tr><td></td></tr>
	      <tr>
		    <td class="diff" align="center"><%= animal.name %></td>
		    <td class="img-quiz"><%= image_tag animal.avatar.url(:thumb) %></td>
		    <td> <audio controls="controls"><source src="<%= animal.sound.url %>" type="audio/mpeg"></audio></td>
		    <td class="s-e-d"><%= link_to 'Show', animal %></td>
		    <% if can? :destroy, Quiz %>
		    <td class="s-e-d"><%= link_to 'Edit', edit_animal_path(animal) %></td>
		    <td class="s-e-d"><%= link_to 'Destroy', animal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		    <% end %>
	      </tr>
	<% end %>
	
  </tbody>
  
</table>

<br>

app/views/animals/new.html.erb
<div class="center-div">

    <table class="transparent" >
    
	<tr><th class="legend">New animal</th></tr>
	<tr><td></td></tr>
	<tr>
	    <td>

		<%= render 'form' %>
		<%= link_to 'Back', animals_path %>

	    </td>
	</tr>

    </table>
    
</div>

app/views/animals/show.html.erb
<table align="center" class="transparent" cellspacing="0">

  <thead>
 
      <tr class="legend">
	  <th>Name</th>
	  <th>Image</th>
	  <th>Sound</th>
	  <th></th>
	  <th></th>
	  <th></th>
      </tr>

  </thead>

  <tbody>

      <tr><td></td></tr>
      <tr>
        <td class="diff"><%= @animal.name %></td>
        <td class="img-quiz"><%= image_tag @animal.avatar.url(:thumb) %></td>
        <td> <audio controls="controls">
	<source src="<%= @animal.sound.url %>" type="audio/mpeg"></audio></td>
        <td class="s-e-d"><%= link_to 'Back', animals_path %></td>
        <% if can? :destroy, Animal %>
	    <td class="s-e-d"><%= link_to 'Edit ', edit_animal_path(@animal) %></td>
	    <td class="s-e-d"><%= link_to 'Destroy ', @animal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>

  </tbody>
  
</table>