config/routes.rb
Zoo::Application.routes.draw do
  resources :settings

  devise_for :users
    
  resources :users

  resources :quizzes

  resources :animals

  get "users/:id/assign_admin_role/" => 'users#assign_admin_role', as: :assign_admin_role
  get "users/:id/remove_admin_role/" => 'users#remove_admin_role', as: :remove_admin_role

  get ":controller/:action"
  
  scope "/pages" do
    get "quizzes/prepare_game" => 'quizzes#prepare_game', :defaults => { :format => 'json' }
  end

  
  root :to => 'pages#home'
  
 # unless Rails.application.config.consider_all_requests_local
  match '*not_found(.*)', to: 'errors#error_404', via: [:get, :post]
 # end


end

app/views/layouts/_user_widget.html.erb
<% if user_signed_in? %>

    <table class="transparent_login" align="right" cellpadding="0" cellspacing="0" border="0">
  
	<tr>
	    <td><%= image_tag("green-circle-th.png", width: '20', height: '20') %></td>
	    <td id="logging"><%= link_to 'Logout '+ current_user.username, destroy_user_session_path, :method => :delete %></td><td id="change-det"><%= link_to "(Change account details)", edit_user_registration_path %></td>
	</tr>

    </table>


<% else %>


    <table class="transparent_logout" align="right" cellpadding="0" cellspacing="0" border="0">
  
	<tr>
	    <td><%= image_tag("red-circle-th.png", width: '20', height: '20') %></td>
	    <td id="logging"><%= link_to 'Login', new_user_session_path %></td>
	</tr>

    </table>


<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>

	    <title>Zoo</title>
	    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	    <%= javascript_include_tag "application", "image_plugin", "data-turbolinks-track" => true %>
	    <%= csrf_meta_tags %>
	    
    </head>

    <body id='back-img'>

	<div id="user_widget"><%= render :partial => 'layouts/user_widget' %></div>

	    <table class="transparent-menu">
	    
		<tr>
		    <td class="menu-text"><%= link_to 'Home', root_url %></td>
		    <td class="menu-text"><%= link_to 'Animals', animals_path %></td> 
		    <td class="menu-text"><%= link_to 'Quizzes', quizzes_path %></td>
		    
		    <% if user_signed_in? %>
			<% if current_user.has_role? :admin %>
			    <td class="menu-text"><%= link_to 'Users', users_path %> </td>
			    <td class="menu-text"><%= link_to 'Settings', settings_path %> </td>
			<% end %>
		    <% end %>
		    
		    <td class="menu-text"><%= link_to 'About', "/pages/about" %> </td>
		</tr>
		
	    </table>
	    
	<div><h1 id="title-zoo"> Indovina Zoo </h1></div>
	    

	<%= yield %>

    
    </body>
</html>